--- 

- name: Configura repo no Ubuntu
  apt:
    deb: https://apt.puppetlabs.com/puppet5-release-xenial.deb
  when: ansible_distribution_release == "xenial"

- name: Configura repo no CentOS 7
  yum:
    name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
    state: present
  when: 
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

