--- 

- name: Instalando Rundeck
  hosts: automation
  tasks:
    - name: Adicionando repositorio
      yum:
        name: http://repo.rundeck.org/latest.rpm
    - name: Instalando Rundeck
      yum:
        name:
          - java
          - rundeck
        state: present
    - name: Inicia o Serviço
      service:
        name: rundeckd
        state: started
