---
# tasks file for prereqs

- name: Garantindo os pacotes básicos para o bluegreen
  package:
    name: 
      - docker-ce
      - nginx
      - python-pip

- name: Instalando docker py
  pip:
    name: docker-py

- name: Garantindo serviços rodando
  service: 
    name: "{{item}}"
    state: started
  with_items:
    - nginx
    - docker


