---

- name: Instala o Apache2 em Debian
  package: 
    name: "{{apache_debian}}"
    state: present
  when:
    ansible_os_family == "Debian"

- name: Instala o Apache2 no CentOS
  package:
    name: "{{apache_centos}}"
    state: present
  notify: 
    - start apache centos
    - disable firewalld
  when: ansible_os_family == "RedHat"


